import type { Metadata } from "next";
import { Inter } from "next/font/google";
import ReduxProvider from "@/components/providers/ReduxProvider";
import Navbar from "@/components/Navbar";
import { Toaster } from "sonner";

import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={`${inter.className} dark:bg-background text-primary flex h-full flex-col bg-white antialiased dark:text-[#adb5bd]`}
      >
        <ReduxProvider>
          <Navbar />
          {children}
        </ReduxProvider>
        <Toaster richColors />
      </body>
    </html>
  );
}
